.PHONY: clean

clean:
	rm ./*.pyc

mongo-creds:
	echo "domain = <domain_creds>" > mongo_creds.py
	echo "port = <port>" >> mongo_creds.py

bitly-creds:
	echo "access_token = '<access_token>'" > bitly_creds.py
